cisagov/dotgov-home

- _data/navigation.yml
- _includes/components/footer.html
- pages/index.md
I added contact info to the footer, and made the logo smaller to fit:
> Add the contact info to the footer, resize the logo

- _includes/components/footer.html
- pages/index.md
This makes it a bit less bare, and provides quick links to important things.
Screenshot:
> Add content to the homepage

- _data/navigation.yml
> Capitalize some words in the banner

- pages/data.md
- pages/faqs.md
- pages/hsts.md
- pages/policy.md
As provided by OGP, improves clarity and wording around the site.
> Make some small content edits

- _includes/components/footer.html
- pages/home.md
> Copyediting

- pages/registration/requirements.md
@nicoleslaw fixing a copy and paste error from last commit.  could you pls review and :thumbsup:?
> updating link to GPO eCFR

- pages/forms/native-sovereign-nation.md
- pages/registration/requirements.md
This change comes from our NSN contact, who asked that her contact info be updated.
> Updating contact info for Native Sovereign Nations

- _includes/scripts.html
- _sass/_custom.scss
Small change to flexbox setup to better support older versions of IE. Also added conditional check on clipboard.js to prevent Javascript error in IE.
**Before:**
**After:**
> Small tweaks for IE support

- _config.yml
- pages/home.md
- pages/registration/requirements.md
This change adds an announcement to the home page that all new federal executive branch domains registrations will be subject to review by OMB. It also makes a minor change on the landing page from "Dotgov.gov" to "DotGov".
> Add February 2018 "recent update"

- _data/navigation.yml
- pages/forms/city.md
- pages/forms/county.md
- pages/forms/federal.md
- pages/forms/interstate.md
- pages/forms/native-sovereign-nation.md
- pages/forms/state.md
- pages/registration/registration.md
- pages/registration/request-templates.md
- pages/registration/requirements.md
In order to support the addition of a forthcoming "interstate" domain type, this change adds an interstate authorization letter template.
> Adding an interstate letter

- _data/navigation.yml
- pages/home.md
- pages/support/2step.md
- pages/support/support.md
This PR adds content for supporting the [.gov registrar](https://home.dotgov.gov)'s move to enable 2-step verification.
> Launching 2-step verification

- Gemfile.lock
- _config.yml
- _includes/components/header.html
Adds search to the navigation bar
Minimum viable
> Adds Search to home.dotgov.gov

- Gemfile.lock
- _config.yml
- _includes/components/header.html
Reverts GSA/dotgov-home#80
Lost the footer!
> Revert "Adds Search to home.dotgov.gov"

- _config.yml
- _includes/components/header.html
2nd pass at adding search to top nav
There is outstanding technical debt to update the dependencies and fix layout, header, footer and base templates (https://github.com/GSA/dotgov-home/pull/80/files)
> Addition of search 

- pages/registration/requirements.md
This change fixes links to Census data in the "City and county exception requests" section of the domain requirements.
> Update Census links

- pages/registration/requirements-precisa.md
- pages/registration/requirements.md
This PR updates the .gov domain requirements, updated in alignment with the DOTGOV Act.
> Update domain requirements

- pages/forms/city-county.md
- pages/registration/requirements.md
This fixes a few small nits with the domain requirements doc and the city/county template.
> Fix link errors

- pages/help/help.md
> Linkify frequently asked questions

- pages/about/elections.md
- pages/home.md
- pages/updates/updates.md
Following #118, this change announces the election page on the home and updates pages.
> Announce election page

- pages/help/help.md
This change broadens the FAQ that was about hosted DNS services to include other services we're often asked about (but don't offer).
> Update FAQ on services that .gov offers

- .bundle/config
- Gemfile.lock
> Bump dependencies

- pages/help/help.md
Fixed a typo, revised, and changed the question title.
> Revise DNS hosting FAQ

- pages/help/help.md
- pages/help/security-best-practices.md
- pages/registration/registration.md
- pages/registration/requirements.md
This update:
* adds FAQs on how to choose a domain name and how many we'll approve
* revises several other FAQs in the DNS section
* adds content to the main registration page regarding name selection/domain hosting and offers a nominal approval timeline
> Winter cleanup

- README.md
- pages/help/help.md
- pages/registration/registration.md
- pages/registration/request-templates.md
This PR adds a line to the authorization letter template page informing potential registrants that approved letters will be shared with the Census Bureau.
...Plus other 3 other very small page edits.
> Add privacy notice to auth template page

- pages/registration/requirements.md
More recent census data is available for reference in determining suffix-less eligibility
> Updated requirements population links

- pages/help/what-to-think-about.md
Wake County's "what's .gov got to do with it" [tweet](https://twitter.com/WakeGOV/status/1625608104284155904) is just too good to not add to the transition guide. This PR also adds the DC Council's nice statement, too.
> Add more examples to transition guide's public comms

- pages/about/elections.md
This updates the About page for elections to clarify the role of election administrators.
> Update elections.md 

- pages/home.md
- pages/updates/2023-transition-email.md
- pages/updates/2023-transition.md
- pages/updates/updates.md
This PR adds the blog "Infrastructure as a (public) service", the email we've sent to registrants, and some navigation helps.
> Add Sept 2023 blog/email on transition

- pages/home.md
A small change that does 3 things:
* Highlights that DNS will still work
* Removes the domain management section that covers sending emails (which we'll add back when emails are sent)
* Adds a "last updated" line with date/time
> Modify home.md for better launch clarity

- pages/home.md
Added a date to status page, moved beta link to the bottom, updated "last updated date."
[Preview link](https://federalist-47d0482b-663e-4928-afca-c2337577b510.sites.pages.cloud.gov/preview/cisagov/dotgov-home/add-date-to-status-page/)
> Add date to status page

- pages/help/help.md
- pages/home.md
- pages/updates/updates.md
Let's make sure our users know the emails they got are legitimate (from our website). Also made the email address a mailto:.
> Launch blurb
