cisagov/dotgov-home

_data/navigation.yml
pages/home.md
pages/support/security.md

This restores the title and URL of `/hsts-preloading/` to the page about HSTS/HTTPS preloading. The primary reason here is for SEO purposes, based on HSTS preloading being something we want to draw extra attention to, particularly among novel audiences (such as other TLDs, and other technical communities of interest).
We may want to restore it to a primary place in the nav in the future, as well for the same reason, but this at least gets the URL and `<title>` tags in place.

Restores original title and link to HSTS preloading page

---

pages/data.md

This PR gets the dotgov home page away from using the `gh-pages` branch of github.com/gsa/data and uses the `master` branch. It also uses the intermediate raw URLs preferred and advertised by GitHub.

Update URLs to use master branch and GitHub's preferred raw URL

---

pages/forms/federal.md

We uploaded the dotgov issuance memo to https://home.dotgov.gov/assets/policies-for-dot-gov-domain-issuance-for-federal-agency-public-websites.pdf, so we can link to a version of it from the form that works.

Update memo URL

---

_layouts/landing.html

This PR moves the definition of the anchor for hero button to be inside the home page file itself.

Drop the relative URL

---

pages/home.md
pages/password-update.md

This change adds a page that outlines the rationale behind making `passwords from public data breaches` unavailable to DotGov users, and gives guidance to users.

Password update page

---

pages/registration/requirements.md

Along with some minor revisions, this change outlines the criteria to allow cities to register a domain name without adding a reference to their state. 
DotGov will arbitrate all exceptions to policy.

Add exception criteria for cities

---

pages/forms/city.md
pages/forms/county.md
pages/forms/federal.md
pages/forms/interstate.md
pages/forms/native-sovereign-nation.md
pages/forms/state.md
pages/forms/us-territory.md

This small change removes the request for a fax number from our authorization letter template.

Remove fax number request from authorization letter templates

---

pages/registration/requirements.md

This change adds a blip about fed.us (no new domains), adds clarity to what we're looking for in interstate domain requests, and fixes a link to census.gov, which they moved.

More words about fed.us, interstate domains and fixing a link

---

pages/home.md
pages/support/security.md

The [.gov registrar](https://domains.dotgov.gov) recently made a change that allows a new domain to opt-in to HSTS preloading at registration. 
This change makes an announcement in "recent updates" and updates the HSTS documentation accordingly.

Announcing HSTS opt-in

---

pages/support/dns.md

OMB [has rescinded](https://www.whitehouse.gov/wp-content/uploads/2018/08/M-18-23.pdf#page=12) the 2008 memo [M-08-23](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2008/m08-23.pdf). This change removes our link to the memo and the text around it.

Remove M-08-23 citation

---

pages/forms/independent-intrastate.md
pages/registration/request-templates.md
pages/registration/requirements.md

This change adds a defined category for "independent intrastate" organizations. I've also attempted a mild revision, aimed at making it easier for each domain type to see the relevant requirements.

Add "independent intrastate" info + revise Requirements narrative

---

pages/home.md

Recent commits shifted where the HSTS preloading explainer was. This PR links it correctly on the home page.

Fix broken link

---

pages/support/2step.md

DotGov only provides customer support for Google Authenticator, but any application that implements the time-based one-time password (TOTP) standard **will** (not _may_) also work.

Added clarity on TOTP

---

pages/support/2step.md

To account for challenges in certain environments, this change shifts enforcement for federal agencies back one month.

Move feds to December

---

pages/support/2step.md

To account for authentication authorization challenges in sensitive environments, this change shifts enforcement for federal agencies back another month and fixes an error for NSN domains (see #68 for both).

Update feds 2-step enforcement to January

---

pages/registration/requirements.md

This tiny update bumps the Census gazetteer file, which we use in evaluating unique city and county names, to the latest version, 2018.

Update gazetteer file

---

_includes/sidenav.html
_sass/_custom.scss

Fixes #93 by removing the `.current-parent` class entirely, which isn't required for the website at all.
Now, the same page renders properly:

Fix sidenav highlighting by removing .current-parent

---

_includes/components/header.html
_sass/lib/uswds/components/_header.scss

It looks like this component isn't needed at all, as removing it
doesn't change anything with the site (except for fixing #63).
Fixes #63

Remove usa-overlay

---

_config.yml
pages/registration/requirements.md

This has two fixes:
* I noticed that `main.css` was being pulled in twice:
I'm honestly not sure where the second source is. This is clearly relying on behavior from [`uswds-jekyll`](https://github.com/18F/uswds-jekyll/blob/master/_includes/styles.html), whose behavior seen in that link shows that it iterates through styles set in a lot of places. The one I removed is the only reference in the project to `styles` I could find, but clearly there's another one (or a default) somewhere. I'm going to guess that `uswds-jekyll` defaults to pulling in a `main.css` itself, making the explicit use in `_config.yml`  unnecessary.
* There's some exposed Markdown on the domain registration requirements, it's missing a URL destination of an anchor link, which I added. It's [visible …

Two small fixes

---

_config.yml
_data/navigation.yml
pages/about/about.md
pages/data.md
pages/forms/city-county.md
pages/forms/federal.md
pages/forms/independent-intrastate.md
pages/forms/interstate.md
pages/forms/native-sovereign-nation.md
pages/forms/state-territory.md
pages/forms/transfers.md
pages/help/help.md
pages/home.md
pages/registration/registration.md
pages/updates/updates.md

This PR adds a link to the .gov RFI, works to make a short, clear case for governments to use gov, and adds an FAQ about election orgs. The language on the data page was also updated.

Add RFI link, update about and FAQ pages

---

pages/help/help.md
pages/registration/requirements.md

This FAQ addresses a common question we've received: whether school districts can use .gov. _While we think .edu should be usable for this purpose_, qualifying 'school district governments' can get a .gov domain.

Add FAQ on school districts

---

_data/navigation.yml
pages/about/about.md
pages/about/elections.md
pages/forms/federal.md
pages/help/help.md
pages/home.md
pages/updates/doing-the-2step.md
pages/updates/intent-to-preload.md

This PR adds an election-specific "about" page to guide the election community through what .gov is, how to get one, and some FAQs. 
For increased clarity, a few updates are also made to pages the new election content links to (help, 2-step, preload). There's also a few small errors fixed (federal, home).

Add election "about" page

---

pages/about/about.md
pages/help/help.md

This change brings some security-centric content that was written for the [elections](https://home.dotgov.gov/about/elections/) page to the about page.

Add security language to about page

---

pages/data.md

GitHub recently [made a change](https://next.github.com/projects/flat-data#part-iii-visualizing-our-data-for-easy-sharing-optional) that adds a nice data viewer to repos with "tabular, non-nested CSV and JSON" files (just prepend `flat` to the domain). 
This PR adds a link to the viewer on our data page.

Add web view with Flat Viewer

---

pages/forms/city-county.md
pages/forms/federal.md
pages/forms/independent-intrastate.md
pages/forms/interstate.md
pages/forms/native-sovereign-nation.md
pages/forms/state-territory.md
pages/forms/transfers.md
pages/help/help.md

As of today, new domain registrations no longer require a billing contact (legacy registrations are unaffected). This PR removes billing contact language from the authorization template letters and the help page.

Remove billing contact mentions

---

pages/updates/2023-transition-email.md

Removed redundant "account" from  `Next, [create a Login.gov account](https://www.login.gov/create-an-account/) account`

Removed redundant "account"

---

_includes/components/banner.html
_sass/_custom.scss

Note: there's duplicate markup for the mobile banner. This should not be an issue semantically or for accessibility (in any case, `display: none` is ignored by SRs).
Local dev env is messed up but I have a pretty good indication that this might work:

Implement a mobile only banner to complement the desktop only one

---

_includes/footer.html
pages/help/help.md
pages/home.md

These updates will be published after the registrar launch. The [status page will be reverted](https://github.com/cisagov/dotgov-home/pull/163) before this PR is merged.
- Updated support email address
- Removed support phone number
- Removed WHOIS link in footer
- Added registrar link on home page and in footer

Post launch updates
